[project]
name = "o2sclpy"
<<<<<<< HEAD
version = "0.931a2"
=======
version = "0.930.1"
>>>>>>> main
authors = [
  { name="Andrew W. Steiner", email="awsteiner0@protonmail.com" },
]
description = "Python extensions for O2scl"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy","matplotlib>=3.1"]
classifiers = [
   "Development Status :: 4 - Beta",
   "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
   "Programming Language :: Python :: 3 :: Only",
   "Topic :: Scientific/Engineering"
]
license = {file = "LICENSE"}
keywords = ["o2scl"]

[project.optional-dependencies]
cli = [
  "yt",
  "scikit-learn",
  "tensorflow",
  "scipy",
  "torch",
  "normflows",
  "ipython",
  "distro"
]

[project.scripts]
o2graph = "o2sclpy.o2graph:o2graph"

[project.urls]
Homepage = "http://awsteiner.org/code/o2sclpy/"
Issues = "https://github.com/awsteiner/o2sclpy/issues"